export const API_REQUEST='API_REQUEST';
export const API_SUCCESS='API_SUCCESS';
export const API_FAILURE='API_FAILURE';


export const FOLLOWERS_API_REQUEST='FOLLOWERS_API_REQUEST';
export const FOLLOWERS_API_SUCCESS='FOLLOWERS_API_SUCCESS';
export const FOLLOWERS_API_FAILURE='FOLLOWERS_API_FAILURE';
